### ISSUE TITLE
网易uu加速器安装错误

### ISSUE THREAD

**Issue by hyou03** [garypang13/OpenWrt_x86-r2s-r4s#434]
opkg install kmod-tun
这个命令输入后显示
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.132-1-b70ee1516753f10c063dd361f74167d4) for kmod-tun

在软件包安装uugamebooster也无法识别路由器。

**Comment by garypang13** [comment]
X86

![image](https://user-images.githubusercontent.com/48883331/126342909-228073d7-f616-45a6-8c8b-9424cf7e77fe.png)

**Comment by hyou03** [comment]
感谢回答，已解决。
